name: Code Review

on: [pull_request]


jobs:
  codeguard:
    runs-on: ubuntu-latest
    name: ChatGPT review PR
    steps:
      - name: ChatGPT review PR
        uses: mzbac/codeguard-gpt-action@HEAD
        with:
          number: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHATGPT_COOKIES: ${{ secrets.CHATGPT_COOKIES }}
          CHATGPT_AUTH_TOKEN: ${{ secrets.CHATGPT_API_KEY }} 
          CODEGUARD_COMMENT_BY_LINE: true
